!$show_upstream_link ?= "false"
!$show_fork_operation ?= "true"
!$show_clone_operation ?= "true"

package GitHub {
  database Origin
  database Upstream
}
package "Your Computer" as Computer {
  database Local
}

!if ($show_fork_operation == "true")
Origin <-[thickness=6] Upstream : Fork
!else
Origin <-[hidden;thickness=6] Upstream : Fork
!endif
Origin ~> Upstream : forked from (link)

!if ($show_clone_operation == "true")
Origin -[thickness=6]-> Local : Clone
!else
Origin -[hidden;thickness=6]-> Local : Clone
!endif
Origin <~~ Local : origin (link)

!if ($show_upstream_link == "true" )
Upstream <~~ Local : upstream (link)
!else
Upstream <~[hidden]~ Local : upstream (link)
!endif
